-- ============================================================================
--  People-Information / Society Directory  —  schema + lockdown
--  Run this ONCE in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query)
--  Safe to re-run: every statement is guarded.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. SOCIETIES  (kills every hardcoded string in the UI)
-- ---------------------------------------------------------------------------
create table if not exists public.societies (
  id                bigint generated by default as identity primary key,
  name              text not null,
  tagline           text,
  address           text,
  city              text,
  pincode           text,
  registration_no   text,
  logo_url          text,
  created_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. MEMBERS  (upgrade the existing table in place, keeping current rows)
-- ---------------------------------------------------------------------------
create table if not exists public.members (
  id          bigint generated by default as identity primary key,
  name        text,
  address     text,
  created_at  timestamptz not null default now()
);

alter table public.members add column if not exists society_id     bigint;
alter table public.members add column if not exists flat_no        text;
alter table public.members add column if not exists block          text;
alter table public.members add column if not exists email          text;
alter table public.members add column if not exists role           text;
alter table public.members add column if not exists is_committee   boolean not null default false;
alter table public.members add column if not exists committee_rank integer not null default 999;
alter table public.members add column if not exists notes          text;
alter table public.members add column if not exists phone          text;

-- The original `contact` column was NUMERIC, which silently destroys real phone
-- numbers (drops leading zeros, rejects "+91" and spaces). Copy it to the new
-- text column, then retire it.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'members' and column_name = 'contact'
  ) then
    update public.members
       set phone = trim(contact::text)
     where phone is null and contact is not null;
    alter table public.members drop column contact;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3. IMPORTANT CONTACTS  (plumber, electrician, security, ambulance, ...)
-- ---------------------------------------------------------------------------
create table if not exists public.important_contacts (
  id            bigint generated by default as identity primary key,
  society_id    bigint,
  category      text not null default 'General',
  label         text not null,
  name          text,
  phone         text,
  alt_phone     text,
  notes         text,
  is_emergency  boolean not null default false,
  display_order integer not null default 999,
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 4. SHARE LINKS  (one row per shareable URL; scope decides what it reveals)
-- ---------------------------------------------------------------------------
create table if not exists public.share_links (
  id          bigint generated by default as identity primary key,
  society_id  bigint,
  token       text not null unique,
  scope       text not null default 'public',
  label       text,
  expires_at  timestamptz,
  revoked     boolean not null default false,
  created_at  timestamptz not null default now(),
  constraint share_links_scope_check check (scope in ('public','residents'))
);

-- ---------------------------------------------------------------------------
-- 5. Adopt any pre-existing rows into a default society
-- ---------------------------------------------------------------------------
do $$
declare v_society_id bigint;
begin
  if not exists (select 1 from public.societies) then
    insert into public.societies (name, tagline)
    values ('My Society', 'Resident directory')
    returning id into v_society_id;
  else
    select id into v_society_id from public.societies order by id limit 1;
  end if;

  update public.members           set society_id = v_society_id where society_id is null;
  update public.important_contacts set society_id = v_society_id where society_id is null;
  update public.share_links       set society_id = v_society_id where society_id is null;

  -- Seed one link of each scope so there is something to copy immediately.
  if not exists (select 1 from public.share_links where scope = 'public') then
    insert into public.share_links (society_id, token, scope, label)
    values (v_society_id, replace(gen_random_uuid()::text,'-',''), 'public',
            'Public — committee & emergency contacts');
  end if;
  if not exists (select 1 from public.share_links where scope = 'residents') then
    insert into public.share_links (society_id, token, scope, label)
    values (v_society_id, replace(gen_random_uuid()::text,'-',''), 'residents',
            'Residents — full directory');
  end if;
end $$;

-- Foreign keys (added after backfill so existing rows do not block them)
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'members_society_fk') then
    alter table public.members
      add constraint members_society_fk foreign key (society_id)
      references public.societies(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'contacts_society_fk') then
    alter table public.important_contacts
      add constraint contacts_society_fk foreign key (society_id)
      references public.societies(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'links_society_fk') then
    alter table public.share_links
      add constraint links_society_fk foreign key (society_id)
      references public.societies(id) on delete cascade;
  end if;
end $$;

create index if not exists members_society_idx  on public.members(society_id);
create index if not exists contacts_society_idx on public.important_contacts(society_id);
create index if not exists links_token_idx      on public.share_links(token);

-- ============================================================================
-- 6. LOCKDOWN
--    RLS on with zero policies = no anon access at all. The public page reaches
--    data only through the SECURITY DEFINER function in section 7, which
--    enforces scope server-side. Editing the URL cannot widen it.
-- ============================================================================
alter table public.societies          enable row level security;
alter table public.members            enable row level security;
alter table public.important_contacts enable row level security;
alter table public.share_links        enable row level security;

revoke all on public.societies          from anon, authenticated;
revoke all on public.members            from anon, authenticated;
revoke all on public.important_contacts from anon, authenticated;
revoke all on public.share_links        from anon, authenticated;

-- ============================================================================
-- 7. The one door anon is allowed through
-- ============================================================================
create or replace function public.get_directory(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_link    public.share_links;
  v_society public.societies;
begin
  if p_token is null or length(p_token) < 8 then
    return jsonb_build_object('error', 'invalid_token');
  end if;

  select * into v_link
    from public.share_links
   where token = p_token
     and revoked = false
     and (expires_at is null or expires_at > now());

  if not found then
    return jsonb_build_object('error', 'invalid_token');
  end if;

  select * into v_society from public.societies where id = v_link.society_id;
  if not found then
    return jsonb_build_object('error', 'invalid_token');
  end if;

  return jsonb_build_object(
    'scope', v_link.scope,
    'society', jsonb_build_object(
      'name',            v_society.name,
      'tagline',         v_society.tagline,
      'address',         v_society.address,
      'city',            v_society.city,
      'pincode',         v_society.pincode,
      'registration_no', v_society.registration_no,
      'logo_url',        v_society.logo_url
    ),
    -- Committee is visible at BOTH scopes: these are published office bearers.
    'committee', coalesce((
      select jsonb_agg(jsonb_build_object(
               'name', m.name, 'role', m.role, 'phone', m.phone,
               'email', m.email, 'flat_no',
               case when v_link.scope = 'residents' then m.flat_no else null end)
             order by m.committee_rank, m.name)
        from public.members m
       where m.society_id = v_link.society_id and m.is_committee
    ), '[]'::jsonb),
    'contacts', coalesce((
      select jsonb_agg(jsonb_build_object(
               'category', c.category, 'label', c.label, 'name', c.name,
               'phone', c.phone, 'alt_phone', c.alt_phone,
               'notes', c.notes, 'is_emergency', c.is_emergency)
             order by c.is_emergency desc, c.display_order, c.label)
        from public.important_contacts c
       where c.society_id = v_link.society_id
    ), '[]'::jsonb),
    -- Full roster ONLY on a residents-scoped link.
    'members', case when v_link.scope = 'residents' then coalesce((
      select jsonb_agg(jsonb_build_object(
               'name', m.name, 'block', m.block, 'flat_no', m.flat_no,
               'phone', m.phone, 'email', m.email, 'role', m.role,
               'address', m.address)
             order by m.block nulls last, m.flat_no nulls last, m.name)
        from public.members m
       where m.society_id = v_link.society_id
    ), '[]'::jsonb) else '[]'::jsonb end
  );
end $$;

revoke all on function public.get_directory(text) from public;
grant execute on function public.get_directory(text) to anon, authenticated;

-- ============================================================================
-- 8. Show the share links to copy into your browser
-- ============================================================================
select scope, label, token, revoked, expires_at from public.share_links order by scope;
